auth:
  google_oauth:
    client_id:
    client_secret:
  oidc:
    client_id:
    client_secret:
    well_known_endpoint:
  scim:
    password:
    username:
  secret_key:
database:
  migrate_token:
deployments:
  azure:
    api_key:
  bedrock:
    access_key:
    secret_key:
    session_token:
  cohere_platform:
    api_key: oBJFDDYQJSArwIHe5NIT1cPEoBVcbREcK58FmnEP
  sagemaker:
    access_key:
    secret_key:
    session_token:
google_cloud:
  api_key:
tools:
  brave_web_search:
    api_key:
  github:
    client_id:
    client_secret:
  gmail:
    client_id:
    client_secret:
  google_drive:
    client_id:
    client_secret:
    developer_key:
  google_web_search:
    api_key:
    cse_id:
  sharepoint:
    client_id:
    client_secret:
  slack:
    client_id:
    client_secret:
  tavily:
    api_key:
  tavily_web_search:
    api_key: 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
  wolfram_alpha:
    app_id:
